export global Theme {
    out property <color> bg: #0e0b00;
    out property <color> surface: #1c1700;
    out property <color> border: #c97a00;
    out property <color> text-primary: #ffaa00;
    out property <color> text-dim: #886600;
    out property <color> accent: #ff6a00;
    out property <color> danger: #cc2200;

    out property <length> border-width: 2px;
    out property <length> font-size-label: 10px;
    out property <length> font-size-body: 13px;
    out property <length> font-size-header: 18px;
}
